In [ ]:
import numpy as np
from numpy import linalg as la

In [ ]:
a=np.array([[6,3],[3,5]])
print(a)
eigenvalues,eigenvectors=la.eig(a)
print(eigenvalues)
print(eigenvectors)
print(la.norm(eigenvectors[:,0]))
print(la.norm(eigenvectors[:,1]))
e1 = eigenvectors[:,0]
e2 = eigenvectors[:,1]
print(np.dot(e1,e2))

[[6 3]
 [3 5]]
[8.54138127 2.45861873]
[[ 0.76301998 -0.6463749 ]
 [ 0.6463749   0.76301998]]
1.0
1.0
9.102881516513367e-18


In [ ]:
a=np.random.rand(3,3)
# print(a)
a=a+a.T
print(a)

v,e=la.eig(a)
print(v)
print('Eigenvectors:')
print('First Eigenvector:')
print(e[:,0])

print('Second Eigenvector:')
print(e[:,1])

print('Third Eigenvector:')
print(e[:,2])

print(np.dot(e[:,0],e[:,1]))
print(np.dot(e[:,1],e[:,2]))

[[0.48580244 0.72813144 1.87927929]
 [0.72813144 0.61186795 0.92078538]
 [1.87927929 0.92078538 0.85489322]]
[ 3.108447   -1.22221508  0.06633169]
Eigenvectors:
First Eigenvector:
[-0.6022448 -0.424907  -0.6758367]
Second Eigenvector:
[-0.72852837 -0.05362479  0.68291346]
Third Eigenvector:
[ 0.32641631 -0.90364729  0.27726156]
-4.79297315894871e-18
-4.12074520554072e-17


In [ ]:
q,r=la.qr(a)
a=r@q
print(a)

[[8.54138127e+00 7.85779780e-11]
 [7.85798151e-11 2.45861873e+00]]
