In [8]:
import numpy as np
from numpy import linalg as la

a = np.array([[6,3],[3,5]])
print(a, '\n')
eigenvalues, eigenvectors = la.eig(a)
print(eigenvalues, '\n')  # the returned eigenvalues are not sorted in any particular manner
print(eigenvectors, '\n') # output of eigenvectors is a row of column eigenvectors (x0 is first column)
print(la.norm(eigenvectors[:,0])) # length of eigenvectors are 1 (eigenvectors are always normalized)
print(la.norm(eigenvectors[:,1]))

e1 = eigenvectors[:,0]
e2 = eigenvectors[:,1]

print(np.dot(e1,e2)) # dot product is zero, the eigenvectors are perpendicular for any symmetric matrix



[[6 3]
 [3 5]] 

[8.54138127 2.45861873] 

[[ 0.76301998 -0.6463749 ]
 [ 0.6463749   0.76301998]] 

1.0
1.0
9.102881516513367e-18


In [17]:
a = np.random.rand(3,3) # random matrix
print (a)
a=a+a.T # sum with transpose to make symmetric
print(a)

v, e = la.eig(a)

print(v)
print('First Eigenvector:')
print(e[:,0])
print('Second Eigenvector:')
print(e[:,1])
print('Third Eigenvector:')
print(e[:,2])

print(np.dot(e[:,0], e[:,1]))
print(np.dot(e[:,1], e[:,2]))

[[0.04394589 0.73647393 0.88134458]
 [0.04322241 0.38959509 0.46136875]
 [0.80291438 0.49836386 0.51305626]]
[[0.08789178 0.77969634 1.68425895]
 [0.77969634 0.77919018 0.9597326 ]
 [1.68425895 0.9597326  1.02611253]]
[ 2.99484919 -1.19243024  0.09077554]
First Eigenvector:
[-0.53194923 -0.48719336 -0.69258404]
Second Eigenvector:
[-0.80165319  0.02631554  0.59720989]
Third Eigenvector:
[ 0.27273097 -0.87289755  0.40455864]
1.212364416339581e-16
-9.132254083014834e-17
