check paper notes for matrix math but basically

for [A] matrix of coeffs, [x] col matrix of variables, [b] col matrix of constants,

[A][x] = [B]

solve by mult [A]^-1 both sides

[A]^-1 [A][x] = [A]^-1 [B]

[I][X] = [X] = [A]^-1[B]


In [10]:
import numpy as np
import scipy as sc

a=np.array([[2,3.7,4],[5,6,-7],[-8,9,10]])
print(a,'\n')

b=a.T # also can use b=np.transpose(a)
print(b, '\n')

c=np.array([[-1,-2,-3]]).T
print(c, '\n')

print(np.linalg.inv(a), '\n')

#matrix mult of A * C
print(a@c, '\n')



[[ 2.   3.7  4. ]
 [ 5.   6.  -7. ]
 [-8.   9.  10. ]] 

[[ 2.   5.  -8. ]
 [ 3.7  6.   9. ]
 [ 4.  -7.  10. ]] 

[[-1]
 [-2]
 [-3]] 

[[ 0.19212746 -0.00156201 -0.07794439]
 [ 0.00937207  0.08122462  0.0531084 ]
 [ 0.1452671  -0.07435177 -0.01015308]] 

[[-21.4]
 [  4. ]
 [-40. ]] 



In [14]:
#2.3x+5.7y-3z=21
#1.3x+0y+5z=4
#-7x-3y+8z=80

A=np.array([[2.3,5.7,-3],[1.3,0,5],[-7,-3,8]])
B=np.array([[21,4,80]]).T
X=np.linalg.inv(A)@B

print(A, '\n', B, "\nSolution\n", X)

[[ 2.3  5.7 -3. ]
 [ 1.3  0.   5. ]
 [-7.  -3.   8. ]] 
 [[21]
 [ 4]
 [80]] 
Solution
 [[-11.51848716]
 [ 10.3292878 ]
 [  3.79480666]]
