# MMAE 350 Homework 1 - Jay Steinberg

## Q1: 
Consider vectors:

$\vec{A} = 2\hat{i} - 3\hat{j} + 7\hat{k}$ \\
$\vec{B} = -4\hat{i} + \hat{j}$ \\
$\vec{C} = 5\hat{i} - \hat{j} + 9\hat{k}$ \\
$\vec{D} = 2\hat{k}$ \\







In [2]:
import numpy as np

A = np.array([2, -3, 7])
B = np.array([-4, 1, 0])
C = np.array([5, -1, 9])
D = np.array([0, 0, 2])

i = np.array([1, 0, 0])
j = np.array([0, 1, 0])
k = np.array([0, 0, 1])

print("Vector A:", A)
print("Vector B:", B)
print("Vector C:", C)
print("Vector D:", D)

Vector A: [ 2 -3  7]
Vector B: [-4  1  0]
Vector C: [ 5 -1  9]
Vector D: [0 0 2]


a) Find $A \cdot B,  C \cdot D $ \\

In [3]:
print("Dot product of A, B: ", np.dot(A, B))
print("Dot product of C, D: ", np.dot(C, D))

Dot product of A, B:  -11
Dot product of C, D:  18



b) The angles which $(A \times B)$ makes with the $x, y, z$ axes \\


In [4]:
E = np.cross(A, B)
print("A x B = ", E)
print("Angle with x-axis: ", np.arccos(np.dot(E,i.T)/(np.linalg.norm(E))))
print("Angle with y-axis: ", np.arccos(np.dot(E,j.T)/(np.linalg.norm(E))))
print("Angle with z-axis: ", np.arccos(np.dot(E,k.T)/(np.linalg.norm(E))))

A x B =  [ -7 -28 -10]
Angle with x-axis:  1.802020934400567
Angle with y-axis:  2.730485267782634
Angle with z-axis:  1.9043313752416218


c) Unit vector in the direction of $(B \times D)$ \\

In [5]:
F = np.cross(B, D)
print("Part C: Unit vector in the direction of (B x D): ", F / np.linalg.norm(F))

Part C: Unit vector in the direction of (B x D):  [0.24253563 0.9701425  0.        ]


d) The vector with the largest magnitude \\

In [6]:
print("Part D: the vector with the largest magnitude: ")
print("Magnitude of A: ", np.linalg.norm(A))
print("Magnitude of B: ", np.linalg.norm(B))
print("Magnitude of C: ", np.linalg.norm(C))
print("Magnitude of D: ", np.linalg.norm(D))

print("Vector C has the largest magnitude.")

Part D: the vector with the largest magnitude: 
Magnitude of A:  7.874007874011811
Magnitude of B:  4.123105625617661
Magnitude of C:  10.344080432788601
Magnitude of D:  2.0
Vector C has the largest magnitude.


## Q2: 
Create two matrices where has at least 3 rows and at least 3 columns and b has at least 2 rows and at least 2 columns. The matrices should not be square and they should not be zero or identity. Make sure that the sizes of the matrices are such that the matrix multiplication can be taken. \\

In [7]:
a = np.array([[4, 3, -2.1], [0.7, -1.1, 5]])
b = np.array([[-2, 1.6],[7, 4],[6.1, -0.2]])

a) Print $a, b, ab$ \\

In [8]:
print("a:")
print(a, "shape ", np.shape(a), '\n')
print("b: ")
print(b, "shape ", np.shape(b), '\n')
print("ab:")
print(a@b)

a:
[[ 4.   3.  -2.1]
 [ 0.7 -1.1  5. ]] shape  (2, 3) 

b: 
[[-2.   1.6]
 [ 7.   4. ]
 [ 6.1 -0.2]] shape  (3, 2) 

ab:
[[ 0.19 18.82]
 [21.4  -4.28]]


b) Is it possible to do the multiplication $aa^T$ ? Why or why not?

Yes, it is possible as any matrix transposed will have the correct match of rows and columns for matrix multiplication.

In [9]:
print(a@a.T)

[[ 29.41 -11.  ]
 [-11.    26.7 ]]


c) Show that $(ab)^T = b^Ta^T$

In [10]:
print((a@b).T, '\n')
print(b.T@a.T)

[[ 0.19 21.4 ]
 [18.82 -4.28]] 

[[ 0.19 21.4 ]
 [18.82 -4.28]]


d) Create two square matrices $c, d$ of equal size and show that $(cd)^{-1} = d^{-1}c^{-1}$


In [11]:
c = np.array([[4, 3],[2, -2]])
d = np.array([[3.2, -2.3],[7, 0.7]])

print("c:")
print(c, '\n')
print("d:")
print(d, '\n')

print("(cd)^-1")
print(np.linalg.inv(c@d), '\n')
print("d^-1 c^-1")
print(np.linalg.inv(d)@np.linalg.inv(c))

c:
[[ 4  3]
 [ 2 -2]] 

d:
[[ 3.2 -2.3]
 [ 7.   0.7]] 

(cd)^-1
[[ 0.02336813 -0.02765228]
 [-0.02959963 -0.13164044]] 

d^-1 c^-1
[[ 0.02336813 -0.02765228]
 [-0.02959963 -0.13164044]]


e) Show that $(c^{-1})^T = (c^T)^{-1}$

In [12]:
print(np.linalg.inv(c).T, '\n')
print(np.linalg.inv(c.T))

[[ 0.14285714  0.14285714]
 [ 0.21428571 -0.28571429]] 

[[ 0.14285714  0.14285714]
 [ 0.21428571 -0.28571429]]


##Q3:
Solve the following system of equations for the variables $x_1, ... x_5:$ \\
 \\
\begin{align*} 
2x_1 + .7x_2 - 3.5x_3 + 7x_4 - .5x_5 = 2 \\
-1.2x_1 + 2.7x_2 - 3x_4 -2.5x_5 = -17 \\
x_1 + x_2 - x_3 - x_4 + x_5 = 5 \\
2.9x_1 + 7.5x_5 = 0 \\
1.8x_3 - 2.7x_4 - 5.5x_5 = -11 \\
\end{align*}

In [41]:
coeffs = np.array([[2, .7, -3.5, 7, -.5],[-1.2, 2.7, 0, -3, -2.5],[1, 1, -1, -1, 1],[2.9, 0, 0, 0, 7.5],[0, 0, 1.8, -2.7, -5.5]])
consts = np.array([[2, -17, 5, 0, -11]]).T
 
print("Original equation coefficients:\n", coeffs, np.shape(coeffs), '\n')
print("Original equation constants:\n", consts, np.shape(consts), '\n')
X = np.linalg.inv(coeffs)@consts
print("Solution:\n", X)

Original equation coefficients:
 [[ 2.   0.7 -3.5  7.  -0.5]
 [-1.2  2.7  0.  -3.  -2.5]
 [ 1.   1.  -1.  -1.   1. ]
 [ 2.9  0.   0.   0.   7.5]
 [ 0.   0.   1.8 -2.7 -5.5]] (5, 5) 

Original equation constants:
 [[  2]
 [-17]
 [  5]
 [  0]
 [-11]] (5, 1) 

Solution:
 [[ -0.56501824]
 [-11.34361865]
 [-12.19151891]
 [ -4.49864426]
 [  0.21847372]]


Show that the calculated solution is indeed correct by substituting in each equation above and making sure that the left hand side equals the right hand side.

In [42]:
newconsts = np.round(coeffs@X, 6)
print("Original constants:\n", consts, '\n')
print("Constants w/ substituted solutions: (rounded to precision 6)\n", newconsts, '\n')
print("Does the substitution match for each equation?\n", newconsts == consts)

Original constants:
 [[  2]
 [-17]
 [  5]
 [  0]
 [-11]] 

Constants w/ substituted solutions: (rounded to precision 6)
 [[  2.]
 [-17.]
 [  5.]
 [  0.]
 [-11.]] 

Does the substitution match for each equation?
 [[ True]
 [ True]
 [ True]
 [ True]
 [ True]]


Clearly we can see that the solution set to the system of equations works properly when reloaded into the original equations.