In [1]:
import numpy as np
import numpy.linalg as la

In [12]:
A = np.array([[0,1,0],
              [1,0,0]])

print(A, '\n')

print(A.T@A, '\n')


u,s,v = la.svd(A)

print(u, '\n\n', np.diag(s), '\n\n', v)

print(la.pinv(A))

[[0 1 0]
 [1 0 0]] 

[[1 0 0]
 [0 1 0]
 [0 0 0]] 

[[1. 0.]
 [0. 1.]] 

 [[1. 0.]
 [0. 1.]] 

 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 1.]
 [1. 0.]
 [0. 0.]]
